-- ============================================================
-- Travel World Colombia — Seed data
-- 8 destinos iniciales + reseñas reales verificadas
-- Imágenes: Unsplash temporal (reemplazar por Supabase Storage)
-- ============================================================

-- ── DESTINOS ──
insert into destinos (slug, activo, destacado, orden, nombre, nombre_local, pais, region,
  frase_hero, autor_frase, cargo_autor, imagen_hero, imagen_thumb, subtitulo, descripcion,
  stats, highlights, galeria, info_clave, precio_desde, incluye, no_incluye, duracion,
  cupos_disponibles, cta_titulo, cta_subtitulo, meta_title, meta_description, keywords)
values

-- 1. República Dominicana (destacado)
('republica-dominicana', true, true, 1, 'República Dominicana', null, 'República Dominicana', 'Caribe',
 'El Caribe que siempre soñaste, todo incluido.', null, null,
 'https://images.unsplash.com/photo-1580541832626-2a7131ee809f?w=1600',
 'https://images.unsplash.com/photo-1580541832626-2a7131ee809f?w=400',
 'Punta Cana · Playas de arena blanca y resorts todo incluido',
 'República Dominicana es el destino #1 más comercializado por las agencias colombianas. Punta Cana ofrece kilómetros de playas de arena blanca, resorts todo incluido de clase mundial y el cálido espíritu caribeño. El plan perfecto para familias, parejas y grupos.',
 '[{"num":"7","label":"Noches"},{"num":"5★","label":"Resorts"},{"num":"28°C","label":"Promedio"},{"num":"#1","label":"Más vendido"}]'::jsonb,
 '[{"icono":"palmtree","titulo":"Isla Saona","descripcion":"Excursión a la paradisíaca isla con almuerzo y bebidas incluidas."},{"icono":"waves","titulo":"Playa Bávaro","descripcion":"Una de las mejores playas del mundo, arena blanca y aguas turquesa."},{"icono":"utensils","titulo":"Todo incluido","descripcion":"Comidas, bebidas y entretenimiento sin preocupaciones."}]'::jsonb,
 '["https://images.unsplash.com/photo-1580541832626-2a7131ee809f?w=800","https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800"]'::jsonb,
 '[{"icono":"plane","label":"Vuelo desde Bogotá","valor":"~4h directo","sub":"Vuelo directo BOG–PUJ"},{"icono":"file-check","label":"Visa colombianos","valor":"No requiere","sub":"Tarjeta de turista incluida"},{"icono":"calendar","label":"Mejor época","valor":"Dic–Abr","sub":"Temporada seca"},{"icono":"wallet","label":"Presupuesto","valor":"desde $899 USD","sub":"Todo incluido"},{"icono":"thermometer","label":"Temperatura","valor":"25–30°C","sub":"Cálido todo el año"}]'::jsonb,
 'desde $899 USD',
 array['Tiquetes aéreos ida y vuelta','Hotel todo incluido','Traslados aeropuerto-hotel','Impuestos hoteleros'],
 array['Gastos personales','Excursiones opcionales','Propinas'],
 '8 días / 7 noches', 6,
 '¿Listo para el Caribe?', 'Cotiza tu plan a Punta Cana hoy mismo',
 'Viaje a República Dominicana desde Colombia | Travel World Colombia',
 'Paquetes todo incluido a Punta Cana desde Colombia ✈️ Tiquetes, hotel y traslados. Cotiza gratis con Travel World Colombia. RNT 27287.',
 array['viaje a republica dominicana desde colombia','paquete punta cana todo incluido colombia','plan republica dominicana 2025','agencia viajes punta cana colombia']),

-- 2. Estados Unidos (destacado)
('estados-unidos', true, true, 2, 'Estados Unidos', null, 'Estados Unidos', 'Norteamérica',
 'El sueño americano está más cerca de lo que crees.', null, null,
 'https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=1600',
 'https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=400',
 'Miami · Orlando · Nueva York',
 'Estados Unidos es el destino #1 de los colombianos: 1.7 millones viajan cada año. Desde las playas de Miami y los parques de Orlando hasta la energía de Nueva York. Te acompañamos también en el proceso de visa.',
 '[{"num":"1.7M","label":"Colombianos/año"},{"num":"29%","label":"Del total"},{"num":"3","label":"Ciudades top"},{"num":"5h","label":"Vuelo"}]'::jsonb,
 '[{"icono":"castle","titulo":"Parques Orlando","descripcion":"Disney World y Universal: magia para toda la familia."},{"icono":"sun","titulo":"Playas de Miami","descripcion":"South Beach, compras y vida nocturna vibrante."},{"icono":"building","titulo":"Nueva York","descripcion":"Times Square, Estatua de la Libertad y Central Park."}]'::jsonb,
 '["https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=800","https://images.unsplash.com/photo-1496588152823-86ff7695e68f?w=800"]'::jsonb,
 '[{"icono":"plane","label":"Vuelo desde Bogotá","valor":"~5h directo","sub":"BOG–MIA / BOG–JFK"},{"icono":"file-check","label":"Visa colombianos","valor":"Requiere visa B1/B2","sub":"Te asesoramos en el trámite"},{"icono":"calendar","label":"Mejor época","valor":"Todo el año","sub":"Según ciudad"},{"icono":"wallet","label":"Presupuesto","valor":"desde $1.290 USD","sub":"Sin visa"},{"icono":"thermometer","label":"Temperatura","valor":"15–30°C","sub":"Varía por región"}]'::jsonb,
 'desde $1.290 USD',
 array['Tiquetes aéreos ida y vuelta','Hotel seleccionado','Traslados','Asesoría de visa'],
 array['Visa americana ($185 USD)','Comidas no especificadas','Entradas a parques'],
 '7 días / 6 noches', null,
 'Tu viaje a USA empieza aquí', 'Cotiza y te asesoramos con la visa',
 'Viaje a Estados Unidos desde Colombia | Travel World Colombia',
 'Paquetes a Miami, Orlando y Nueva York desde Colombia ✈️ Tiquetes, hotel y asesoría de visa. Cotiza gratis. RNT 27287.',
 array['viaje a estados unidos desde colombia','paquete miami colombia todo incluido','plan orlando disney desde colombia','visa estados unidos agencia colombia']),

-- 3. España
('espana', true, false, 3, 'España', null, 'España', 'Europa',
 'Historia, tapas y la mejor cultura europea.', null, null,
 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=1600',
 'https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=400',
 'Madrid · Barcelona · Sevilla',
 'España recibe más de 812.000 colombianos al año. El idioma común, la riqueza histórica y la gastronomía hacen de España el portal perfecto a Europa. Madrid, Barcelona, Sevilla y la Costa del Sol.',
 '[{"num":"812K","label":"Colombianos/año"},{"num":"+5.7%","label":"Crecimiento"},{"num":"4","label":"Ciudades"},{"num":"10h","label":"Vuelo"}]'::jsonb,
 '[{"icono":"landmark","titulo":"Madrid histórico","descripcion":"Museo del Prado, Plaza Mayor y el Palacio Real."},{"icono":"church","titulo":"Sagrada Familia","descripcion":"La obra maestra de Gaudí en Barcelona."},{"icono":"wine","titulo":"Tapas y vino","descripcion":"Gastronomía española auténtica en cada rincón."}]'::jsonb,
 '["https://images.unsplash.com/photo-1539037116277-4db20889f2d4?w=800","https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800"]'::jsonb,
 '[{"icono":"plane","label":"Vuelo desde Bogotá","valor":"~10h directo","sub":"BOG–MAD"},{"icono":"file-check","label":"Visa colombianos","valor":"Requiere visa Schengen","sub":"Te asesoramos"},{"icono":"calendar","label":"Mejor época","valor":"Abr–Jun · Sep–Oct","sub":"Clima templado"},{"icono":"wallet","label":"Presupuesto","valor":"desde $1.690 USD","sub":"Sin visa"},{"icono":"thermometer","label":"Temperatura","valor":"15–30°C","sub":"Mediterráneo"}]'::jsonb,
 'desde $1.690 USD',
 array['Tiquetes aéreos','Hoteles céntricos','Traslados','City tours'],
 array['Visa Schengen','Comidas','Entradas a museos'],
 '9 días / 8 noches', null,
 'Descubre España', 'Tu puerta de entrada a Europa',
 'Viaje a España desde Colombia | Travel World Colombia',
 'Paquetes a Madrid, Barcelona y Sevilla desde Colombia ✈️ Tiquetes, hotel y tours. Cotiza gratis. RNT 27287.',
 array['viaje a espana desde colombia','paquete madrid barcelona colombia','plan europa espana 2025','agencia viajes espana colombia']),

-- 4. Panamá
('panama', true, false, 4, 'Panamá', null, 'Panamá', 'Centroamérica',
 'Compras, canal y playas a un paso de Colombia.', null, null,
 'https://images.unsplash.com/photo-1558029062-a37889b87526?w=1600',
 'https://images.unsplash.com/photo-1558029062-a37889b87526?w=400',
 'Ciudad de Panamá · Canal · Compras',
 'Panamá creció un 20% como destino de colombianos (341.734 viajeros). Famoso por sus compras libres de impuestos, el icónico Canal y su moderna capital. El escape internacional más rápido y económico desde Colombia.',
 '[{"num":"341K","label":"Colombianos/año"},{"num":"+20%","label":"Crecimiento"},{"num":"1.5h","label":"Vuelo"},{"num":"USD","label":"Moneda"}]'::jsonb,
 '[{"icono":"ship","titulo":"Canal de Panamá","descripcion":"Una de las maravillas de la ingeniería moderna."},{"icono":"shopping-bag","titulo":"Compras","descripcion":"Multiplaza y Albrook Mall, libres de impuestos."},{"icono":"building-2","titulo":"Casco Antiguo","descripcion":"Historia colonial y vida nocturna en la capital."}]'::jsonb,
 '["https://images.unsplash.com/photo-1558029062-a37889b87526?w=800"]'::jsonb,
 '[{"icono":"plane","label":"Vuelo desde Bogotá","valor":"~1.5h directo","sub":"BOG–PTY"},{"icono":"file-check","label":"Visa colombianos","valor":"No requiere*","sub":"Con visa US/Schengen vigente"},{"icono":"calendar","label":"Mejor época","valor":"Dic–Abr","sub":"Temporada seca"},{"icono":"wallet","label":"Presupuesto","valor":"desde $649 USD","sub":"Económico"},{"icono":"thermometer","label":"Temperatura","valor":"26–32°C","sub":"Tropical"}]'::jsonb,
 'desde $649 USD',
 array['Tiquetes aéreos','Hotel','Traslados','Tour del Canal'],
 array['Compras','Comidas','Excursiones opcionales'],
 '5 días / 4 noches', 8,
 'Escápate a Panamá', 'El plan internacional más cercano',
 'Viaje a Panamá desde Colombia | Travel World Colombia',
 'Paquetes a Ciudad de Panamá desde Colombia ✈️ Canal, compras y playas. Tiquetes, hotel y traslados. Cotiza gratis. RNT 27287.',
 array['viaje a panama desde colombia','paquete panama compras colombia','plan ciudad de panama 2025','agencia viajes panama colombia']),

-- 5. Brasil
('brasil', true, false, 5, 'Brasil', null, 'Brasil', 'Suramérica',
 'Río, samba y las playas más vibrantes del continente.', null, null,
 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=1600',
 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=400',
 'Río de Janeiro · Salvador · Playas',
 'Brasil tuvo un crecimiento del 49.8% como destino en 2025. Río de Janeiro, el Cristo Redentor, las playas de Copacabana e Ipanema y la energía contagiosa del país más grande de Suramérica.',
 '[{"num":"+49.8%","label":"Crecimiento 2025"},{"num":"6h","label":"Vuelo"},{"num":"38","label":"Playas top"},{"num":"No visa","label":"Colombianos"}]'::jsonb,
 '[{"icono":"mountain","titulo":"Cristo Redentor","descripcion":"Una de las 7 maravillas del mundo moderno."},{"icono":"waves","titulo":"Copacabana","descripcion":"La playa más famosa del mundo y su malecón."},{"icono":"music","titulo":"Cultura carioca","descripcion":"Samba, gastronomía y la alegría brasileña."}]'::jsonb,
 '["https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=800","https://images.unsplash.com/photo-1516306580123-e6e52b1b7b5f?w=800"]'::jsonb,
 '[{"icono":"plane","label":"Vuelo desde Bogotá","valor":"~6h","sub":"BOG–GIG vía conexión"},{"icono":"file-check","label":"Visa colombianos","valor":"No requiere","sub":"Hasta 90 días turismo"},{"icono":"calendar","label":"Mejor época","valor":"Dic–Mar","sub":"Verano brasileño"},{"icono":"wallet","label":"Presupuesto","valor":"desde $1.090 USD","sub":"Todo incluido parcial"},{"icono":"thermometer","label":"Temperatura","valor":"25–35°C","sub":"Tropical"}]'::jsonb,
 'desde $1.090 USD',
 array['Tiquetes aéreos','Hotel frente al mar','Traslados','City tour Río'],
 array['Comidas','Excursiones opcionales','Propinas'],
 '7 días / 6 noches', null,
 'Vive Brasil', 'Río te está esperando',
 'Viaje a Brasil desde Colombia | Travel World Colombia',
 'Paquetes a Río de Janeiro desde Colombia ✈️ Cristo Redentor, Copacabana y más. Tiquetes, hotel y tours. Cotiza gratis. RNT 27287.',
 array['viaje a brasil desde colombia','paquete rio de janeiro colombia','plan brasil 2025','agencia viajes brasil colombia']),

-- 6. Japón
('japon', true, true, 6, 'Japón', '日本', 'Japón', 'Asia',
 'Donde la tradición milenaria se encuentra con el futuro.', null, null,
 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1600',
 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=400',
 'Tokio · Kioto · Monte Fuji',
 'Japón es el destino aspiracional por excelencia. Tokio futurista, los templos de Kioto, el Monte Fuji y la cultura del respeto y la perfección. Una experiencia transformadora al otro lado del mundo.',
 '[{"num":"24h","label":"Vuelo"},{"num":"2","label":"Ciudades icónicas"},{"num":"3.776m","label":"Monte Fuji"},{"num":"★★★★★","label":"Experiencia"}]'::jsonb,
 '[{"icono":"torii","titulo":"Templos de Kioto","descripcion":"Fushimi Inari y sus miles de puertas torii rojas."},{"icono":"building","titulo":"Tokio futurista","descripcion":"Shibuya, Akihabara y la tecnología de vanguardia."},{"icono":"mountain-snow","titulo":"Monte Fuji","descripcion":"La montaña sagrada y símbolo de Japón."}]'::jsonb,
 '["https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=800","https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800"]'::jsonb,
 '[{"icono":"plane","label":"Vuelo desde Bogotá","valor":"~24h","sub":"Con conexiones"},{"icono":"file-check","label":"Visa colombianos","valor":"Requiere visa","sub":"Te asesoramos en el trámite"},{"icono":"calendar","label":"Mejor época","valor":"Mar–May · Oct–Nov","sub":"Sakura y otoño"},{"icono":"wallet","label":"Presupuesto","valor":"desde $3.290 USD","sub":"Premium"},{"icono":"thermometer","label":"Temperatura","valor":"10–25°C","sub":"4 estaciones"}]'::jsonb,
 'desde $3.290 USD',
 array['Tiquetes aéreos','Hoteles seleccionados','Japan Rail Pass','Tours guiados en español'],
 array['Visa japonesa','Comidas no especificadas','Gastos personales'],
 '10 días / 9 noches', 4,
 'Descubre Japón', 'Un viaje que cambia tu vida',
 'Viaje a Japón desde Colombia | Travel World Colombia',
 'Paquetes a Tokio y Kioto desde Colombia ✈️ Monte Fuji, templos y más. Tiquetes, hotel y tours. Cotiza gratis. RNT 27287.',
 array['viaje a japon desde colombia','paquete tokio kioto colombia','plan japon 2025','agencia viajes japon colombia']),

-- 7. París
('paris', true, false, 7, 'París', null, 'Francia', 'Europa',
 'La ciudad del amor, el arte y la elegancia.', null, null,
 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1600',
 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400',
 'Torre Eiffel · Louvre · Versalles',
 'París, la capital del romance. La Torre Eiffel, el Museo del Louvre, los Campos Elíseos y el Palacio de Versalles. El destino europeo más soñado por las parejas colombianas.',
 '[{"num":"11h","label":"Vuelo"},{"num":"324m","label":"Torre Eiffel"},{"num":"#1","label":"Romance"},{"num":"35K","label":"Obras Louvre"}]'::jsonb,
 '[{"icono":"tower","titulo":"Torre Eiffel","descripcion":"El símbolo de París iluminado al anochecer."},{"icono":"palette","titulo":"Museo del Louvre","descripcion":"La Mona Lisa y miles de obras maestras."},{"icono":"crown","titulo":"Versalles","descripcion":"El palacio más opulento de Europa y sus jardines."}]'::jsonb,
 '["https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800","https://images.unsplash.com/photo-1431274172761-fca41d930114?w=800"]'::jsonb,
 '[{"icono":"plane","label":"Vuelo desde Bogotá","valor":"~11h directo","sub":"BOG–CDG"},{"icono":"file-check","label":"Visa colombianos","valor":"Requiere visa Schengen","sub":"Te asesoramos"},{"icono":"calendar","label":"Mejor época","valor":"Abr–Jun · Sep–Oct","sub":"Primavera y otoño"},{"icono":"wallet","label":"Presupuesto","valor":"desde $1.890 USD","sub":"Sin visa"},{"icono":"thermometer","label":"Temperatura","valor":"10–25°C","sub":"Templado"}]'::jsonb,
 'desde $1.890 USD',
 array['Tiquetes aéreos','Hotel céntrico','Traslados','City tour París'],
 array['Visa Schengen','Comidas','Entradas a atracciones'],
 '7 días / 6 noches', null,
 'París te espera', 'El viaje más romántico',
 'Viaje a París desde Colombia | Travel World Colombia',
 'Paquetes a París desde Colombia ✈️ Torre Eiffel, Louvre y Versalles. Tiquetes, hotel y tours. Cotiza gratis. RNT 27287.',
 array['viaje a paris desde colombia','paquete paris francia colombia','plan paris romantico 2025','agencia viajes paris colombia']),

-- 8. Santorini
('santorini', true, false, 8, 'Santorini', null, 'Grecia', 'Europa',
 'El atardecer más hermoso del mundo te espera.', null, null,
 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=1600',
 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=400',
 'Oia · Fira · Caldera',
 'Santorini, la joya del Egeo. Sus casas blancas con cúpulas azules, los atardeceres de Oia y las aguas cristalinas hacen de esta isla griega el destino más fotografiado y romántico del Mediterráneo.',
 '[{"num":"13h","label":"Vuelo"},{"num":"#1","label":"Atardecer"},{"num":"Egeo","label":"Mar"},{"num":"★★★★★","label":"Luna de miel"}]'::jsonb,
 '[{"icono":"sunset","titulo":"Atardecer en Oia","descripcion":"El ocaso más famoso y romántico del planeta."},{"icono":"home","titulo":"Casas blancas","descripcion":"La arquitectura cicládica icónica de cúpulas azules."},{"icono":"sailboat","titulo":"Crucero por la Caldera","descripcion":"Navega el volcán y baña en aguas termales."}]'::jsonb,
 '["https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800","https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=800"]'::jsonb,
 '[{"icono":"plane","label":"Vuelo desde Bogotá","valor":"~13h","sub":"Con conexión vía Atenas"},{"icono":"file-check","label":"Visa colombianos","valor":"Requiere visa Schengen","sub":"Te asesoramos"},{"icono":"calendar","label":"Mejor época","valor":"May–Sep","sub":"Verano griego"},{"icono":"wallet","label":"Presupuesto","valor":"desde $2.290 USD","sub":"Premium"},{"icono":"thermometer","label":"Temperatura","valor":"20–30°C","sub":"Mediterráneo"}]'::jsonb,
 'desde $2.290 USD',
 array['Tiquetes aéreos','Hotel con vista a la caldera','Traslados','Crucero por el volcán'],
 array['Visa Schengen','Comidas','Excursiones opcionales'],
 '8 días / 7 noches', 5,
 'Santorini de ensueño', 'El destino perfecto para tu luna de miel',
 'Viaje a Santorini desde Colombia | Travel World Colombia',
 'Paquetes a Santorini, Grecia desde Colombia ✈️ Oia, atardeceres y caldera. Tiquetes, hotel y tours. Cotiza gratis. RNT 27287.',
 array['viaje a santorini desde colombia','paquete grecia santorini colombia','plan santorini luna de miel 2025','agencia viajes grecia colombia'])

on conflict (slug) do nothing;


-- ── RESEÑAS REALES VERIFICADAS (Google) ──
insert into resenas (nombre, texto, estrellas, destino, activa, orden, fuente)
values
('ANCA Pina',     'Agencia seria, responsable y cumplida. Hemos viajado varias veces y siempre nos ha ido bien.', 5, null, true, 1, 'google'),
('Aleidy Gomez',  'Ya hemos viajado en varias oportunidades y todo ha sido perfecto. Super recomendados.',          5, null, true, 2, 'google'),
('Laura Reyes',   'Nos acompañaron en todo momento, muy cumplidos con el hotel y el itinerario.',                  5, null, true, 3, 'google'),
('Jhon Albeiro',  'Excelente atención desde la partida hasta la llegada. 100% Recomendada.',                       5, null, true, 4, 'google'),
('Familia cliente','Plan México-Cancún perfecto. Siempre amables y pendientes durante todo el viaje.',           5, 'mexico', true, 5, 'google')
on conflict do nothing;
